### ISSUE TITLE
Node14 EOL

### ISSUE THREAD

**Issue by brendanclement** [mooyoul/aws-cdk-ses-domain-identity#81]
Node14 has reached EOL and AWS lambda will stop supporting this runtime on Feb 8, 2024

See: https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html#runtime-support-policy

After this date, lambda functions using NodeJS 14 cannot be created, and shortly after that, functions cannot be updated.  We need to bump the version used in this package to NodeJS 18

**Comment by mooyoul** [comment]
Hello there, I've just released v2.2.0 which uses Node.js v20 runtime.

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/aws-cdk-ses-domain-identity/v/2.2.0)
- [GitHub release](https://github.com/mooyoul/aws-cdk-ses-domain-identity/releases/tag/v2.2.0)

(btw package release pipeline which uses semantic-release, had some issues - v2.1.0 was published as incomplete state. Please use v2.2.0 instead of v2.1.0)
Thanks for your patience and Happy new year!
